### ISSUE TITLE
[Missing Release]: Add .zip Option for Windows plugin release 

### ISSUE THREAD

**Issue by Trouffman** [obs-ndi/obs-ndi#1003]
### Describe the bug

The .zip install package is missing for the Obs-ndi installation on Windows on release : [obs-ndi 4.13.1](https://github.com/obs-ndi/obs-ndi/releases/tag/4.13.1)

Also : Add the list of Package / bundle expected to the development steps so we do not miss it anymore.

Source : As reported by !MANJIT on the Discord Server.

If you want to get OBS-NDI for the OBS in portable mode.

- Install obs-ndi via the regular install.
- Confirm files are copied to your OBS portable folder
- enjoy.

Note : You will STILL nee dto install the NDI Lib/Runtime on the Computer you will be iusing this OBS Portable.

**Comment by BitRate27** [comment]
I was able to fix the script in my PR, but do not know where to update the "development steps".

**Comment by Trouffman** [comment]
@BitRate27 this is fixed and the the 4.13.2 has the zip attached too as well.

**Comment by BitRate27** [comment]
The .zip file is there in 4.13.2, but it was missing the installer.exe file. I saw this bug report, where the title is different than the description (missing installer in the .zip file), and noticed someone else noticed the same thing. The PR fixes the Installer build script so that the zip file is complete. Maybe I misunderstood the bug. Apologies.

**Comment by Trouffman** [comment]
All good! Thanks for sharing your findings :)
