### ISSUE TITLE
[Bug]: The checksums for the latest release of OBS-NDI 4.13.2 do not match the packages

### ISSUE THREAD

**Issue by saltarob** [obs-ndi/obs-ndi#1010]
### Operating System Version

MacOS 14.4.1

### OBS Version

30.1.2

### OBS Installation Method

pkg

### OBS-NDI Version

4.13.2

### OBS-NDI Installation Method

pkg

### NDI Version

4.13.2

### Describe the bug

shasum -a256 obs-ndi-4.13.2-macos-universal.pkg 
fe3d054399bb104afe67a9751702950995ce53f76c660647b44e3287cceb4bcc  /Users/abdulhadi/Downloads/obs-ndi-4.13.2-macos-universal.pkg

Does not match the posted checksum:

obs-ndi-4.13.2-macos-universal.pkg: df0fa515c585d105188c91bf14089fa391044f478dce52844927b7140a6e8467

**Comment by paulpv** [comment]
Good catch!

Yes, I totally botched this release when I first kicked off 4.13.2 and then it failed because our Apple Developer Account expired and then after fixing the account it went downhill when **I re-ran the same build that failed over a week earlier instead of kicking off a whole new build**.
That cascaded into a botched release of first not all artifacts being there, and then when I fixed that I forgot to correct the checksums.

Sorry all.

Should be fixed now.

Please confirm.

**Comment by saltarob** [comment]
Yes, the checksum for the macOS package is correct now. Thank you so much. May it be easy for you. Wish you the best.

**Comment by saltarob** [comment]
So, I am closing the Issue.
