### ISSUE TITLE
macOS > runtime installer link is dead

### ISSUE THREAD

**Issue by jlocca** [obs-ndi/obs-ndi#1029]
Hi. The link for the runtime installer for macOS is dead. Is a new link available?

Thank you.

> Install the NDI 4.5.1 macOS runtime using the installer provided here: https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

**Comment by MarximusMaximus** [comment]
Attached is a zip of the the above file, will need somewhere to host it though. I don't seem to have the windows version handy.

[ndi-runtime-4.5.1-macOS.pkg.zip](https://github.com/obs-ndi/obs-ndi/files/15410775/ndi-runtime-4.5.1-macOS.pkg.zip)

**Comment by paulpv** [comment]
1. How did you open an issue without going through the template?
2. What version of OBS are you running?
3. (Related to # 2) Where did you get that link from?
4. That link is intentionally deprecated
5. No, we do not want to host any NDI runtimes, especially not one that is years old and that would/should not work with the latest version of the plugin.

**Comment by jlocca** [comment]
> 1. How did you open an issue without going through the template?
I opened a ticket here in Github. Which template are you referring to, please? I'm a noob who is not seeing the expected results with this OBS + NDI Tools combination, and I'd like to ask via the appropriate channels.  

<img width="1253" alt="Screenshot 2024-05-23 at 09 23 58" src="https://github.com/obs-ndi/obs-ndi/assets/16841852/0554dbac-8a23-4b7a-9b60-69d65a9509c8">

> 2. What version of OBS and OBS-NDI are you running?
OBS 30.1.2
NDI Launcher version 1.0 (19)

> 3. (Related to # 2) Where did you get that link from?
I'm a noob who found it in the description of this (amateurish and incomplete) YouTube tutorial:
https://youtu.be/Ofp5W0Ztjjs?si=FdoLRfLtoS_LaV_f

>    The link was added in [81a7cee](https://github.com/obs-ndi/obs-ndi/commit/81a7cee4765691ca560cb7aba161c0f9468bef75) (2020/04/10) and removed in [9e494e6](https://github.com/obs-ndi/obs-ndi/commit/9e494e6078a1663f0f849410eda4852a35fe1cf3) (2023/02/27)
> 4. That link is intentionally deprecated
> 5. No, we do not want to host any NDI runtimes, especially not one that is years old and that would/should not work with the latest version of the plugin.
> 6. The latest supported runtime is already updated in the code:
>    https://github.com/obs-ndi/obs-ndi/blob/master/data/locale/en-US.ini#L51-L53
> 
> ```
> NDIPlugin.RedistUrl.Win="http://ndi.link/NDIRedistV5"
> NDIPlugin.RedistUrl.MacOS="http://ndi.link/NDIRedistV5Apple"
> NDIPlugin.RedistUrl.Linux="https://github.com/obs-ndi/obs-ndi/blob/master/CI/libndi-get.sh"
> ```
> 
So, are you saying that I should not have to install a runtime after installing NDI Tools?

>  8. To get the latest runtime just follow the appropriate link
Thank you!

**Comment by jlocca** [comment]
> Attached is a zip of the the above file, will need somewhere to host it more permanently though. I don't seem to have the windows version handy.
> 
> [ndi-runtime-4.5.1-macOS.pkg.zip](https://github.com/obs-ndi/obs-ndi/files/15410775/ndi-runtime-4.5.1-macOS.pkg.zip)

**Comment by paulpv** [comment]
You provided links to two videos:
https://youtu.be/Ofp5W0Ztjjs
https://m.youtube.com/watch?v=Rqajo6a6s1c

Both of those videos are over 2 years old and provide a direct link to https://github.com/obs-ndi/obs-ndi/releases/tag/4.9.0
A lot has changed in 2 years.

You must use https://github.com/obs-ndi/obs-ndi/releases/latest

OBS-NDI requires OBS and the NDI Runtime.

NDI Tools is not the NDI Runtime.
To add to the confusion, installing NDI Tools installs the NDI Runtime installer into the NDI Tools installation folder, but does not actually install the NDI Runtime.
This is NDI confusion, not ours.

Installing NDI Tools is recommended, since it comes with NDI Studio Monitor and NDI Screen Capture.

But, you do not have to install NDI Tools to get the NDI Runtime installer.
The latest code will detect the absence of NDI Runtime and prompt you to install the NDI Runtime using these values: 
```
NDIPlugin.RedistUrl.Win="http://ndi.link/NDIRedistV5"
NDIPlugin.RedistUrl.MacOS="http://ndi.link/NDIRedistV5Apple"
NDIPlugin.RedistUrl.Linux="https://github.com/obs-ndi/obs-ndi/blob/master/CI/libndi-get.sh"
```

An upcoming OBS-NDI 6.0 release will use these values: 
* http://ndi.link/NDIRedistV6
* http://ndi.link/NDIRedistV6Apple
* https://github.com/obs-ndi/obs-ndi/blob/develop/CI/libndi-get.sh

**Comment by MarximusMaximus** [comment]
IF someone comes here needing windows 4.5.1 for using an old version against and old OBS, here is a copy of mine that seeeeeems to work if I just put it in the right place. I had to format+reinstall Windows the other day so I lost my install and don't have the installer. I installed 5.x and it obviously didn't work with OBS 27.x and old matching ndi-obs plugin. Then I dropped this folder in place and it worked. This folder is from a backup I did of Program Files on prior Windows install. YMMV. Good luck!

Extract this to "C:\Program Files\" (you should end up with a folder named "NewTek").

[NewTek.zip](https://github.com/user-attachments/files/16277652/NewTek.zip)
