### ISSUE TITLE
Feature Req: Scale output in filter

### ISSUE THREAD

**Issue by Fire-** [obs-ndi/obs-ndi#144]
I'd like to be able to have the NDI output filter itself scale the output feed. 

Currently you can partially get away with this by chaining a scale filter before the NDI output filter, but then you're left with a scaled source for your visible OBS scene, which is lackluster and prevents locally recording at native res.

**Comment by nt3rp** [comment]
I understand that this is an enhancement request, but @Fire- ... could you elaborate on what you've written?

I ask because it sounds like you _might_ have a workaround and I'm currently running into an issue with Skype where, due to bandwidth, the resolution can fluctuate (same aspect ratio but different resolution).

**Comment by Trouffman** [comment]
Hard to find examples of use-cases for this Feature Requests.

The up/downscaling can be achieved in a dedicated OBS or via a dedicated scene.
