### ISSUE TITLE
A bunch of colorspace issues

### ISSUE THREAD

**Issue by matiaspl** [obs-ndi/obs-ndi#186]
What I see currently (on a Macbook Pro with most recent plugin and NDI redist) is that:
a) in the the NDI source the "default" YUV range and color space seems to be fixed to 601+partial,
b) preview and program NDI outputs use different color spaces/color conversions/color matrices,
c) NDI preview output isn't 709 nor 601 (I always get a picture that shifts to green more with 601 or less with 709),
d) the same goes for Dedicated NDI output, it works better with 709/partial
e) it's impossible to get 1:1 color reproduction with Newtek NDI Scan Converter - here 709/partial works better too,
BUT:
f) main NDI output+NDI input has perfect color reproduction even after 20+ encoding-decoding iterations 

Test setup/how to reproduce:
Enabled main and preview NDI outputs,
Two "Vertigo" scenes that do infinite video loopback with RGB ARIB bars in the back and NDI input in front (first with program input, second one with preview).
Digital Color Meter tool on OSX for confidence monitoring ;)

![Program](https://user-images.githubusercontent.com/1915126/42451423-84436a1a-8387-11e8-89c5-23c548de260a.png)
![Preview](https://user-images.githubusercontent.com/1915126/42451424-846c4ad4-8387-11e8-9508-19397f25fa93.png)

NDI program/main output shows correct colors as long as the input YUV Range&Color space settings are the same as the output settings. 
E.g. since the correct setup for youtube is (or seems to be) 709+partial, if one wants to use NDI with those settings enabled under OBS advanced settings, the same has to be used when adding reentry NDI inputs to the scene.

**Comment by matiaspl** [comment]
I think the problem is with the colorspace being used "under the hood" for all sources (and scenes) except output. I'm guessing this is either chroma subsampling error or a spatial chroma shift due to YUV format misinterpretation. The chroma problems can be seen below on green and red letters and also inside the 709/601 matrix verification box:

Image only: ![zrzut ekranu 2018-07-10 13 08 34](https://user-images.githubusercontent.com/1915126/42506551-7d195018-8442-11e8-9037-8d1866946510.png)

Image -> Dedicated NDI fiter -> NDI Source: ![zrzut ekranu 2018-07-10 13 08 43](https://user-images.githubusercontent.com/1915126/42506552-7d342bb8-8442-11e8-956b-cacaeca6b19d.png)

**Comment by Palakis** [comment]
@matiaspl 
> a) in the the NDI source the "default" YUV range and color space seems to be fixed to 601+partial,

That's a possibility. I haven't checked how `VIDEO_CS_DEFAULT` and `VIDEO_RANGE_DEFAULT` are handled in libobs.

> b) preview and program NDI outputs use different color spaces/color conversions/color matrices,
c) NDI preview output isn't 709 nor 601 (I always get a picture that shifts to green more with 601 or less with 709),

Ah, I see what's likely the issue here: preview output is BGRA video converted to YUV by the NDI library. Problem is, I possibly have no control on the range and colorspace used by the NDI library. One solution would be to do the RGB->YUV conversion on OBS` side.

> d) the same goes for Dedicated NDI output, it works better with 709/partial

Same issue as the preview output: it's BGRA video converted to YUV by the NDI library.

> f) main NDI output+NDI input has perfect color reproduction even after 20+ encoding-decoding iterations

Thanks to the range and colorspace settings of the NDI input!

**Comment by Palakis** [comment]
Btw, thanks for this comprehensive report!

**Comment by Palakis** [comment]
@matiaspl 
> a) in the the NDI source the "default" YUV range and color space seems to be fixed to 601+partial,

You're right. Here's what the [libobs docs](https://github.com/obsproject/obs-studio/blob/d51e2a019bb6c166731800f25de035b1f99891f3/docs/sphinx/reference-libobs-media-io.rst) say:

> VIDEO_CS_DEFAULT - Equivalent to VIDEO_CS_601
[...]
VIDEO_RANGE_DEFAULT - Equivalent to VIDEO_RANGE_PARTIAL

**Comment by Palakis** [comment]
I'll remove the "default" values for range and colorspace, as they can be misleading.

**Comment by Palakis** [comment]
It's probably already fixed but I'm putting this on the backlog for 4.8.0, just in case.

**Comment by mattbeghin** [comment]
I'm confronted to the same issue. If I use library RGB=>YUV conversion for output and use any of the YUV->RGB conversion described here: https://en.wikipedia.org/wiki/YCbCr#Y'CbCr_to_xvYCC
I can't get the same colors. I'm interested to understand what is the NDI library YUV color space. If I use the NDI lib with RGB as output and RGB as input, the loop looks good. So it doesn't seem there's a bug in the lib, but I can't find any information in their documentation...

**Comment by mattbeghin** [comment]
Sorry for my last post. My conversions were wrong since I was not rescaling Y & V from limited range to full range before matrix multiplications. I could sort it.
Per the NDI Advanced SDK Documentation (19.1 Video Frames) SD resolutions use BT.601, HD (xres>720 || yres>576) use Rec.709, and UHD (xres>1920 || yres>1080) use Rec.2020

Details here: https://forums.newtek.com/threads/ndi-lib-yuv-color-profile.166803/
I can now get the exact same color getting NDI stream in YUV and converting with shader than when requesting RGB from NDI library.

**Comment by Trouffman** [comment]
Closing this, it seems to be resolved or is too old to re-check on new ONS + OBS-NDI + NDI Version & SDK.
