### ISSUE TITLE
NDI desync over time (Mac iOS) 

### ISSUE THREAD

**Issue by OGfent** [obs-ndi/obs-ndi#375]
Hi, 

I have been using the NDI plugin to stream my Elgato HD60s through OBS. 

Unfortunately I have experienced audio desync over time, every single stream. Usually happens about 20minutes into a stream. Now i know this is a big issue that there have been a bunch of fixes for, however none of them have worked for me. 

I am currently running "internal" and normal latency. OBS , Elgato & NDI is all up to date using the newest updated versions. 

Attempts to fix include: 
- Muting the main NDI source and adding an additional  'audio only' source. 
- Doing the above and using the 'monitor' function on OBS 
- Installing updates, old / new OBS versions. 
- Changing from 'internal' to 'network' 
- Enabling / disabling hardware acceleration

I am losing my mind with this and after spending a good £160.00 on my capture i just want this working!

Any suggestions or help with this would be greatly appreciated. 

Thank you

**Comment by Helgaiden** [comment]
When i experienced any desync, i would just  close OBS on the main PC and re-open it and that would take care of it. Have you tried that?

**Comment by OGfent** [comment]
yes, i have tried that but whilst you're Live on twitch it is very unprofessional and is annoying having to do it every 30 mins of a 10 hour stream.

**Comment by Helgaiden** [comment]
Nothing unprofessional about throwing up a Be Right Back scene on the streaming PC to restart OBS on the main PC.

Good luck.

**Comment by OGfent** [comment]
unless like last night there is an issue with obs. 

Thanks for the "advice" though mate, made the situation so much better.

**Comment by Helgaiden** [comment]
You're welcome, anytime.

**Comment by JBraddockm** [comment]
Hi,

I also have a similar issue. Initially, I assumed that the issue was something to do with Skype. But I did more testing and it seems that it is not caused by Skype. Below is what I did to test the problem:

- I installed the demo version of [NDI ScanConverter](http://www.sienna-tv.com/ndi/ndi-scanconverter.html) on my laptop and route the audio as expected. Unlike the NDI's official app, this one allows you to set framerate, which I thought could be important for debugging the issue.

- On my laptop, I get the best performance by choosing 1280*720, Pre-Scaled, 30 or 60fps. 

- I created a virtual audio input and routed the audio accordingly in the app. This allows you to send the audio via NDI.

- Both my laptop and streaming computer - iMac - have wired ethernet connections.

When I bring this NDI output into Wirecast on my iMac, there is no sync issue. Even for some reasons the connection stutters, the audio still remains intact.

If, on the other hand, I bring the same NDI output into OBS, regardless of which sync options I choose in the plugin's settings, the audio eventually drifts.

So far, the only solution for me is to switch between sync options of the plugin. In other words, if "internal" is selected and the audio drifts, changing it to Source Timings fixes it until it drifts again and vice versa.

I hope this is helpful. 

Let me know if I can do anything else for you.

Regards.

**Comment by unknowndomain** [comment]
I've had the exact issue @JBraddockm is describing Skype goes out of sync regardless of sync option, I've found that switching sync options mid stream fixes the issue but it' quickly goes out again.

**Comment by unknowndomain** [comment]
@Palakis I have flagged this issue with Elgato Support as it comes up in #mac-os support on Discord all the time but their staff were not interested in helping to fix this issue until their customers come to them complaining.

**Comment by Lownin** [comment]
Not sure if this is helpful, but when I mute the audio source in OBS on the NDI receiving end, the audio doesn't stop immediately if I am in a desynced state.  The lag seems to be client-side somehow.

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing due to no response and release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
