### ISSUE TITLE
Installing obs-ndi

### ISSUE THREAD

**Issue by nicklmarks** [obs-ndi/obs-ndi#397]
Hello, 

I am trying to test a dual PC streaming setup and I am having an issue with the installation.
I was attempting to follow the linux installation instructions here. https://github.com/Palakis/obs-ndi/releases/tag/4.7.1

 1771  sudo rm libndi.so
 1772  sudo ln -r -s libndi.so.4.0.0 libndi.so
 1773  sudo rm libndi.so.4
 1774  sudo ln -r -s libndi.so.4.0.0 libndi.so.4
I tried to first update the symlinks as this may have been causing an initial error.

Please advise. Thanks!

```
Ubuntu/Debian
Manual install (64-bit only): Download libndi3_4.0.0-1_amd64.deb and obs-ndi_4.7.1-1_amd64.deb, and install them on your system.
When I tried to install with the software manager libndi3_4.0.0-1_amd64.1.deb seemed to be corrupt... I can't find a way to un-install this package.

```
~$ obs -v
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Command Line Arguments: -v
info: CPU Name: AMD A8-5500 APU with Radeon(tm) HD Graphics
info: CPU Speed: 1800.000MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 7374MB Total, 3839MB Free
info: Kernel Version: Linux 4.4.0-142-generic
info: Distribution: "Ubuntu" "14.04"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.18.3
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 23.1.0 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org Gallium 0.4 on AMD ARUBA (DRM 2.43.0, LLVM 3.8.0)
info: OpenGL loaded successfully, version 4.1 (Core Profile) Mesa 11.2.0, shading language 4.10
info: ---------------------------------
info: video settings reset:
	base resolution:   1366x768
	output resolution: 1092x614
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
info: No blackmagic support
info: [obs-ndi] hello ! (version 4.7.1)
obs: symbol lookup error: /usr//lib/obs-plugins/obs-ndi.so: undefined symbol: _ZN7QString13toUtf8_helperERKS_

**Comment by Palakis** [comment]
@nicklmarks Ubuntu 14.04 seems fairly old. Did you try this on a recent Ubuntu version?

**Comment by jasonhendry** [comment]
I've been an occasional user of ubuntu for a while, feel free to take my comments FWIW

Using Ubuntu 18.04, I installed the plugin the same way I install most things.
`
sudo apt install libndi4_4.5.1-1_amd64.deb
sudo apt install obs-ndi_4.7.1-1_amd64.deb
`
Now, there's a couple caveats:

1. I vaguely recall having to hunt around to get the plugin in the right place, it eventually landed here:
`/usr/lib/obs-plugins`
when properly configured your're obs logfile looks like:
`
10:25:23.363: CPU Name: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
10:25:23.364: CPU Speed: 1599.942MHz
10:25:23.364: Physical Cores: 4, Logical Cores: 4
10:25:23.364: Physical Memory: 7961MB Total, 5680MB Free
10:25:23.364: Kernel Version: Linux 5.3.0-46-generic
10:25:23.364: Distribution: "Ubuntu" "18.04"
10:25:23.365: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.5
10:25:23.368: Portable mode: false
10:25:23.481: OBS 25.0.4 (linux)
10:25:23.481: ---------------------------------
10:25:23.482: ---------------------------------
10:25:23.482: audio settings reset:
10:25:23.482: 	samples per sec: 44100
10:25:23.482: 	speakers:        2
10:25:23.513: ---------------------------------
10:25:23.513: Initializing OpenGL...
10:25:23.671: Loading up OpenGL on adapter NVIDIA Corporation GeForce GT 710/PCIe/SSE2
10:25:23.671: OpenGL loaded successfully, version 3.3.0 NVIDIA 435.21, shading language 3.30 NVIDIA via Cg compiler
10:25:23.727: ---------------------------------
10:25:23.728: video settings reset:
10:25:23.728: 	base resolution:   1920x1080
10:25:23.728: 	output resolution: 1280x720
10:25:23.728: 	downscale filter:  Bicubic
10:25:23.728: 	fps:               30/1
10:25:23.728: 	format:            NV12
10:25:23.728: 	YUV mode:          601/Partial
10:25:23.728: NV12 texture support not available
10:25:23.731: Audio monitoring device:
10:25:23.731: 	name: Default
10:25:23.731: 	id: default
10:25:23.731: ---------------------------------
10:25:23.737: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
10:25:24.033: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
10:25:24.033: No blackmagic support
10:25:24.221: NVENC supported
10:25:24.221: FFMPEG VAAPI supported
10:25:24.236: [obs-ndi] hello ! (version 4.8.0)
10:25:24.236: [obs-ndi] Trying ''
10:25:24.237: [obs-ndi] Trying '/usr/lib'
10:25:24.237: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
10:25:24.250: [obs-ndi] NDI runtime loaded successfully
10:25:24.252: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 00:05:02 Apr  1 2020 4.5.1)
10:25:24.293: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: cannot open shared object file: No such file or directory
10:25:24.293: 
10:25:24.293: Couldn't find VLC installation, VLC video source disabled
10:25:24.293: ---------------------------------
10:25:24.293:   Loaded Modules:
10:25:24.293:     vlc-video.so
10:25:24.293:     text-freetype2.so
10:25:24.293:     rtmp-services.so
10:25:24.293:     obs-x264.so
10:25:24.293:     obs-transitions.so
10:25:24.293:     obs-outputs.so
10:25:24.293:     obs-ndi.so
10:25:24.293:     obs-libfdk.so
10:25:24.293:     obs-filters.so
10:25:24.293:     obs-ffmpeg.so
10:25:24.293:     linux-v4l2.so
10:25:24.293:     linux-pulseaudio.so
10:25:24.293:     linux-jack.so
10:25:24.293:     linux-decklink.so
10:25:24.293:     linux-capture.so
10:25:24.293:     linux-alsa.so
10:25:24.293:     image-source.so
10:25:24.293:     frontend-tools.so
10:25:24.293:     decklink-ouput-ui.so
10:25:24.293: ---------------------------------
10:25:24.294: ==== Startup complete ===============================================
10:25:24.302: All scene data cleared
10:25:24.302: ------------------------------------------------
10:25:24.308: pulse-input: Server name: 'pulseaudio 11.1'
10:25:24.309: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
10:25:24.309: pulse-input: Started recording from 'alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor'
10:25:25.728: pulse-input: Server name: 'pulseaudio 11.1'
10:25:25.729: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
10:25:25.729: pulse-input: Started recording from 'alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor'
10:25:25.737: [obs-ndi] started A/V threads for source 'ELARA (NDI HX Camera)'
10:25:25.737: [obs-ndi] A/V thread for 'iphone' started
10:25:25.756: [obs-ndi] started A/V threads for source '--- (rekordbox)'
10:25:25.756: [obs-ndi] A/V thread for 'new rk' started
10:25:25.761: [obs-ndi] started A/V threads for source '--- (Avenue -  Composition)'
10:25:25.761: [obs-ndi] A/V thread for 'NDI™ Source' started
10:25:25.823: Switched to scene 'abenues'
10:25:25.824: ------------------------------------------------
10:25:25.824: Loaded scenes:
10:25:25.824: - scene 'abenues':
10:25:25.824:     - source: 'new rk' (ndi_source)
10:25:25.824:     - source: 'NDI™ Source' (ndi_source)
10:25:25.824: - scene 'bideos':
10:25:25.824:     - source: 'iphone' (ndi_source)
10:25:25.824:     - source: 'Image' (image_source)
10:25:25.824: ------------------------------------------------
`
2. I can't get the iPhone NDI app to stream to the plugin
The plugin sees the app, but no audio or video are coming through.  I'll write up an issue on this elsewhere.

Otherwise, it works like a treat!  I use both NDI Scan Converter and vMix Desktop Capture to stream Audio and Video to my Ubuntu OBS (25.x.x) successfully to Facebook, Twitch and YouTube.

Thanks Palakis.

**Comment by jasonhendry** [comment]
Ah, I see this is a known issue.  I won't opena new ticket.

https://github.com/Palakis/obs-ndi/issues/129#issuecomment-524377315

**Comment by nicklmarks** [comment]
> @nicklmarks Ubuntu 14.04 seems fairly old. Did you try this on a recent Ubuntu version?

I did not end up testing Ubuntu versions but as I was working I found some of the issues are related to upgrades to the Kernel. I was also testing on another Windows machine and got it to work. I can provide updates if I try again with Ubuntu. Thank you for this tool and will provide updates if I am able to test and debug anything.

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?
