### ISSUE TITLE
4.9 installer flagged by Microsoft SmartScreen and other AVs

### ISSUE THREAD

**Issue by KovalevArtem** [obs-ndi/obs-ndi#455]
![image](https://user-images.githubusercontent.com/36500228/80222839-179ea500-8650-11ea-895c-5ecc817770ca.png)
https://www.virustotal.com/gui/file/ee0293379d7b0ca9d072ffc1bceb735333354ea353516220d24637ad75b0808a/detection
What is the problem that some antiviruses do not like the installation file?

**Comment by StephanBeer** [comment]
Same here on Windows 10 with Avast free. Avast is blocking the installer, showing "idp.alexa.51"

**Comment by KovalevArtem** [comment]
Virustotal 4.9.0-Windows-Installer.exe
![image](https://user-images.githubusercontent.com/36500228/80578405-120adb80-8a11-11ea-800a-fdc697c0cf2a.png)

https://www.virustotal.com/gui/file/b024f933dc1e5298543ca06e443b5d37231e204affae7fb520155e0933801630/detection

**Comment by duncangeere** [comment]
I'm also getting a virus warning when trying to install on Windows.

**Comment by mkono87** [comment]
Same with 4.8  cant install.

**Comment by shanselman** [comment]
You can submit here https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Palakis** [comment]
@shanselman Thanks! I did that yesterday night. Looks like it's good now, at least for Microsoft: https://www.microsoft.com/en-us/wdsi/submission/4178125f-3641-47af-9d6d-ab64d5f37cb4

**Comment by RoyceRemix** [comment]
Norton also stopped the Windows installer during installation for me; appears to be while creating a shortcut for "obs-ndi on the Web.url" within the AppData folder.  Norton clears the installer as being fine before running it.

![image](https://user-images.githubusercontent.com/97641735/224197694-bf666c3e-f4d6-4aaf-8293-5f9826da9dac.png)
![image](https://user-images.githubusercontent.com/97641735/224197791-a28508d6-fd04-43df-b6bb-588872e1d186.png)

Sorry my high-contrast dark mode settings on Windows makes the Norton text a little hard to read.  What is the solution?  Why is this getting grabbed?

**Comment by paulpv** [comment]
Looks like that `obs-ndi on the Web.url` file is coming from:
https://github.com/search?q=repo%3Aobs-ndi%2Fobs-ndi+ProgramOnTheWeb&type=code

I have zero idea why that would flag a virus.

**Comment by paulpv** [comment]
I think I see why.

The default install script code installs a generic shortcut:
 ```
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
```

The default value of `MyAppURL` is:
```
#define MyAppURL "http://www.mywebsite.com"
```

After installing I do see that shortcut in my Start Menu.
![image](https://user-images.githubusercontent.com/1393897/224407321-49c7d8ff-ee69-4b17-bb9f-c439a67e35ef.png)

Launching it browses to http://www.mywebsite.com, which is an unfortunate choice because that looks like a poorly convincing phishing site:
![image](https://user-images.githubusercontent.com/1393897/224407533-32b99ec6-39fa-4a86-848f-9176da498f2e.png)

I presume that changing the default URL to https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/ will fix the problem.

**Comment by paulpv** [comment]
I opened https://github.com/obsproject/obs-plugintemplate/issues/70
