### ISSUE TITLE
Is NDI causing OBS to crash?

### ISSUE THREAD

**Issue by jg1273** [obs-ndi/obs-ndi#543]
Last couple of times I have streamed, OBS has crashed.  Below I have attached my crash logs.  Any help?
[Crash 2020-08-09 10-32-58.txt](https://github.com/Palakis/obs-ndi/files/5086852/Crash.2020-08-09.10-32-58.txt)
[Crash 2020-08-16 11-25-11.txt](https://github.com/Palakis/obs-ndi/files/5086853/Crash.2020-08-16.11-25-11.txt)
[Crash 2020-08-16 11-25-33.txt](https://github.com/Palakis/obs-ndi/files/5086854/Crash.2020-08-16.11-25-33.txt)

**Comment by nettings** [comment]
The first log shows that the crash happens in a system library (c:\windows\system32\d3d11.dll),  not in OBS.
Maybe try to update your DirectX.
But before you do that, uninstall obs-ndi and see if your stream session still crashes. If it doesn't then yes, your problem might be obs-ndi-related. If it does, your problem is elsewhere.

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
