### ISSUE TITLE
[Q&A] Newbie Corner

### ISSUE THREAD

**Issue by cdavid14** [obs-ndi/obs-ndi#547]
Hello everyone, i've down here by parachute with a NDI needing that the tv channel that i work now have, and i have some questions about the plugin byself, if you guys can help-me i'll thank alot.

So the questions:
1- The NDI Output is encoded? (I've checked an NDI Output bitrate and looks like a VBR with something around 100~160mb)
2- There's a GPU support for NDI or just CPU use? (not around implemented stuff, but around possibilities, we use NDI with laptops and CPU use kill them)

**Comment by nettings** [comment]
1. Yes. Uncompressed HD video would not fit through a gigabit network link. However, since the link uses a lot of bandwidth, encoding and decoding is very efficient.
2. I don't know. But I can easily run OBS on an old-ish Thinkpad X230, grab a fullscreen youtube session in a browser and send it on via NDI without the system breaking too much of a sweat. Firefox runs at 21% CPU, OBS (and NDI) at 10%. So I have 60+ percent on one core left, and 100% of the other core. Perfectly usable.

**Comment by nettings** [comment]
Also, do not abuse the bug tracker for support questions :-D Maybe sign up for the OBS forums, I guess they are a more appropriate place...
