### ISSUE TITLE
NDI Audio distorted

### ISSUE THREAD

**Issue by nettings** [obs-ndi/obs-ndi#548]
Sending an A/V NDI stream from  
OBS 25.0.8/obs-ndi 4.9.0 on Windows 10 Rev 2004  
to  
OBS 25.0.7-575-gaef10d46/obs-ndi c7252018dc38a081d350b8963db899ed629e5055 on openSUSE Tumbleweed,   
I get recognizable but severely distorted audio.
The problem might be on the Windows end, because the first thing that I noticed was that audio captured from the default output was going way over 0dB (which shouldn't be possible with no system gains above 0 dB, which I checked). But the distortion persisted even as I brought down the fader(s) in OBS, or in the player (in this case a browser running youtube).
The issue is the same when using a VLC source.
Listening to the sources on the Windows side over laptop loudspeakers, they are all ok. A short test recording in the source OBS yields correct sound as well.

My NDI source on the Linux (=receiver) side is operating at "highest bandwidth". I tried low and normal latency, network and source sync, and "allow hardware acceleration" on/off. None of these seemed to affect the issue. The problem persists even at "Audio only" bandwidth, and the video stream is flawless, so that would rule out network congestion, I guess.

I don't really understand how audio synchronisation in NDI works - both OBS instances use 48k as their sample rate, but at some point resampling must occur, because their clocks cannot be perfectly in sync, unless "network sync" does just that, like with Dante or AES67. But the distortion is too severe anyways to be "just" clock drift - that would be a small click every once in a while.
Unfortunately I couldn't download my own NDI SDK and tools yet, because their "give me your data and I'll mail you a link" stuff doesn't work at the moment .... :(

**Comment by nettings** [comment]
Forgot to mention: when I record a short test video on the OBS source, the sound is ok.

**Comment by nettings** [comment]
Would it be possible for a network endianness swap to have crept in somewhere? I remember it can sound like what I'm hearing...

**Comment by nettings** [comment]
I just tested sending from my Windows system (versions see above) to another Windows system, same versions, and it worked flawlessly. So the problem is either some subtle incompatibility between the latest windows release and the latest git versions, or maybe some network issue between Linux and Windows. I'll spin up a Linux laptop, get the build environment going, and see if I can stream from latest git to latest git....

**Comment by nettings** [comment]
From Linux to Linux, both ends current git of obs-studio and obs-ndi, sound is distorted.

**Comment by nettings** [comment]
From Linux latest git to Windows NDI Monitor, sound is ok.

**Comment by nettings** [comment]
After some more testing, I think I can re-state the issue: NDI Audio reception is broken on latest OBS git on Linux...

**Comment by Trouffman** [comment]
Did you check with OBS-NDI release 4.9.1 ?
That release target linux OS Specifically.

**Comment by popcorn9499** [comment]
Just figured it might be worth adding to this since I believe I was having the same issue with audio distortion at least I thought I was. Turned out audio monitoring for the ndi stream was screwed up. Any other audio device seemed to play back find that I tested. However the recording of the audio sounded just fine which leads me to believe its something specific to audio monitoring. 

I am running the latest release packages on the [AUR ](https://aur.archlinux.org/packages/obs-ndi/) 4.9.1-2 at the time of writing

OBS Studio Version 27.0.0.rc5.r9.g8cf28ceaf on arch linux.

Hopefully this can help solve whatever strangeness is going on or at least provide a solution for someone looking at this in the future

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Related to #549 ? I think there are several other "distorted" type of related issues.

**Comment by Trouffman** [comment]
They could be all related but they are ALL on old version of OBS / plugin / runtime.
This could be tested as part of our v6 release. Until then, closing this as "stale".

Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
