### ISSUE TITLE
OBS Studio crashes w/ plugin

### ISSUE THREAD

**Issue by PiscesGamer97** [obs-ndi/obs-ndi#600]
Every time I launch OBS Studio v26.0.2 with NDI 4.9.0 (4.9.1 Ubuntu fix) it closes itself, it doesn't even say "Whoops! OBS Studio has crashed! Send this report log?" It just closes itself with the plugin installed.
OBS Studio with StreamElements OBS.Live add-on
NDI 4 Runtime
obs-ndi 4.9.0
Windows 10 Pro v20H2
CPU R3 2200G
RAM (2x4)8GB Team Group
MOBO ASRock x370 PRO4
iGPU
When I uninstall obs-ndi plugin it's fine

**Comment by gr01d** [comment]
A temp fix is to use OBS 32 bit

**Comment by Trouffman** [comment]
Does the same behavior exist witht he latest release 26.1 ?

Please consider providing the log file as well they are located in : %AppData%\obs-studio\logs

**Comment by tocan** [comment]
@Trouffman all the forums in OBS Mac are full of complaints and the tips when they are given are mainly to fake users.

Please provide a complete Deinstallation Routine very soon because some resources did provide links to resources that are for shire not trustful. Apple when I did try one close access to AppStore.
Before I install I like to clean my system. I stay with Mojave because I need Controllermade and they do not support Catalina.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
