### ISSUE TITLE
[Bug]: Obs-NDI causing NDI to leak memory

### ISSUE THREAD

**Issue by tzerber** [obs-ndi/obs-ndi#898]
### Operating System Version

OBS running Windows 10, NDI capture running Windows 11

### OBS Version

Tested with 28.1, 29.1.3

### NDI Tools Version

Tested with 4.6 and 5.5.4.0

### Describe the bug

Once OBS-NDI start receiving NDI signal the NDI hosts start's eating it's memory with 7-8 megabytes / second until the PC runs out of ram and crashes the NDI proccess. The issue does not happen with another NDI program like Studio Monitor or VLC.

### Steps to reproduce

1) PC 1 (win 11, relatively recent machine) with attached camera, launch screen capture, set the settings for desired resolution and frame rate.
2) PC 2 (win 10, overkill machine for OBS) launch OBS studio, add NDI source, add the source from PC 1. No need to do anything else.
3) Open task manager on PC 1 and just watch how your ram gets eaten.
4) After your PC runs out of ram you will see some random application crash log in windows console, extremely unhelpful one. Basically it tells you the app crashed and it has no idea why

### Expected behavior

It's okay to take some gigabytes if needed, but it's a very good idea to free them up after a while.

### Screenshots

![image](https://github.com/obs-ndi/obs-ndi/assets/26799548/79ee9aa4-71db-4dd7-a3ab-d539195eea8a)

**Comment by paulpv** [comment]
@tzerber I tried this with my latest [not yet released] 4.12.0 version on Windows 11 and I do not see any memory leaks while receiving a live NDI stream for over an hour.
Memory started at 430MB, jumped a little to 470MB, and then dropped back to 340MB and is sitting steady.
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/6b5ca5a9-bb36-4540-88df-1bdede8d66d6)

I will soon release a 4.12.0 version w/ updated NDI lib that might help/avoid this leak.

You can try out 4.12.0 Release Candidate if you want.

The Pull Request https://github.com/obs-ndi/obs-ndi/pull/919 has been labeled with "Seeking Testers" and the build generates installer packages that you can download try out.

Steps:
1. Browse to https://github.com/obs-ndi/obs-ndi/pull/919
2. Click on "Show all checks"
3. Click on any of the "Details"
4. Click on "Summary"
5. Scroll down and see the "Artifacts"
6. Download the relevant Linux/MacOS/Windows artifact for your platform
7. Windows may complain that the download looks suspicious; you may safely ignore 
8. Unzip the download
9. Run the installer

Closing for now and due to the age of this Issue.
Feel free to re-open if you still see a memory leak.

**Comment by tzerber** [comment]
That's what i call timing. I am preparing another event that require the use of OBS-NDI, and i will be able to properly test this in few days. This issue can stay closed for now, but i will surely come back with results as well as i will respond to anything required/optional in the "Seeking tests" area.

**Comment by SosaXIII** [comment]
I just updated to NDI 6 and tried Screen Capture HX. This caused massive memory leak while displaying nothing.

- Switching to normal Screen Capture worked
- Switching to NDI 5 using normal Screen Capture worked
- Switching to NDI 5 using Screen Capture HX didn't show any picuture, but also did NOT cause memory leak

**Comment by RayneYoruka** [comment]
HX still behaves in a lot of weird ways.. avoid it if possible when combining with obs-ndi

**Comment by tzerber** [comment]
I kinda forgot about that, but when i last tested it - it was still leaking like a garden hose. Will do some tests in the next days and post some results.

**Comment by Trouffman** [comment]
@tzerber - If you can compile : check with this fork : https://github.com/Trouffman/obs-ndi/tree/NDI6-Update
This is using the NDI6 SDK, check if still happening.
